# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import cart_pb2 as cart__pb2


class CartServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetCartDetails = channel.unary_unary(
                '/CartService/GetCartDetails',
                request_serializer=cart__pb2.CartRequest.SerializeToString,
                response_deserializer=cart__pb2.CartResponse.FromString,
                )


class CartServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetCartDetails(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CartServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetCartDetails': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCartDetails,
                    request_deserializer=cart__pb2.CartRequest.FromString,
                    response_serializer=cart__pb2.CartResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'CartService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class CartService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetCartDetails(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/CartService/GetCartDetails',
            cart__pb2.CartRequest.SerializeToString,
            cart__pb2.CartResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
