// LOGIN
export const LOGIN = 'LOGIN'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAILED = 'LOGIN_FAILED'

//  LOGOUT
export const LOGOUT = 'LOGOUT';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';

// REGISTER
export const REGISTER = 'REGISTER'
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'
export const REGISTER_FAILED = 'REGISTER_FAILED'

// AUTH TOKEN
export const GET_AUTH_INFO = 'GET_AUTH_INFO';
export const GET_AUTH_INFO_SUCCESS = 'GET_AUTH_INFO_SUCCESS';
export const GET_AUTH_INFO_401 = 'GET_AUTH_INFO_401';

// ITEM BY USER
export const GET_ITEM_USER = "GET_ITEM_USER";
export const GET_ITEM_USER_SUCCESS = "GET_ITEM_USER_SUCCESS";
export const GET_ITEM_USER_FAILED = "GET_ITEM_USER_FAILED";

// ITEM ALL
export const GET_ITEM = "GET_ITEM";
export const GET_ITEM_SUCCESS = "GET_ITEM_SUCCESS";
export const GET_ITEM_FAILED = "GET_ITEM_FAILED";

// ITEM DETAIL
export const GET_DETAIL_ITEM = "GET_DETAIL_ITEM";
export const GET_DETAIL_ITEM_SUCCESS = "GET_DETAIL_ITEM_SUCCESS";
export const GET_DETAIL_ITEM_FAILED = "GET_DETAIL_ITEM_FAILED";

// CREATE ITEM
export const CREATE_ITEM = "CREATE_ITEM";
export const CREATE_ITEM_SUCCESS = "CREATE_ITEM_SUCCESS";
export const CREATE_ITEM_FAILED = "CREATE_ITEM_FAILED";

// DELETE ITEM
export const DELETE_ITEM = "DELETE_ITEM";
export const DELETE_ITEM_SUCCESS = "DELETE_ITEM_SUCCESS";
export const DELETE_ITEM_FAILED = "DELETE_ITEM_FAILED";

// UPDATE ITEM
export const UPDATE_ITEM = "UPDATE_ITEM";
export const UPDATE_ITEM_SUCCESS = "UPDATE_ITEM_SUCCESS";
export const UPDATE_ITEM_FAILED = "UPDATE_ITEM_FAILED";

// ADD ITEM TO CART
export const ADD_ITEM = "ADD_ITEM";
export const ADD_ITEM_SUCCESS = "ADD_ITEM_SUCCESS";
export const ADD_ITEM_FAILED = "ADD_ITEM_FAILED";

// GET CART
export const GET_CART = 'GET_CART'
export const GET_CART_SUCCESS = 'GET_CART_SUCCESS'
export const GET_CART_FAILED = 'GET_CART_FAILED'
